apiVersion: 1
datasources:
  - name: SmartGrid Postgres
    uid: smartgrid-pg
    type: grafana-postgresql-datasource
    access: proxy
    url: postgres:5432
    user: grafana_ro
    isDefault: true
    jsonData:
      database: smartgrid
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    secureJsonData:
      password: grafana_ro

  - name: Prometheus
    uid: smartgrid-prom
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    jsonData:
      timeInterval: 10s
